name: Building Ad Service

# Only trigger, when the build workflow succeeded
on:
  workflow_run:
    workflows: ["Continuous Integration - Push"]
    branches: [master]
    types:
      - completed

jobs:
  build-ad-service:
    runs-on: ubuntu-latest

    steps:

      - name: Login to ACR
        uses: azure/docker-login@v1
        with:
          login-server: boutiqueaksacr.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }} 
      
      - name: Building Ad Service
        run: |
          cd ../src/adservice/
          docker build -t boutiqueaksacr.azurecr.io/adservice:v1 .
          docker push boutiqueaksacr.azurecr.io/adservice:v1