name: 'Building Ad service image'

on:
  push:
    branches:
    - master
    paths:
      - "src/adservice/"

jobs:
  Integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: ACTIONS_ALLOW_UNSECURE_COMMANDS
        id: ACTIONS_ALLOW_UNSECURE_COMMANDS
        run: echo 'ACTIONS_ALLOW_UNSECURE_COMMANDS=true' >> $GITHUB_ENV

      - name: Import Secrets
        uses: hashicorp/vault-action@v2.0.1
        with:
          url: http://vault.centralus.cloudapp.azure.com:8200/
          token: ${{ secrets.VAULT_TOKEN }}
          tlsSkipVerify: true
          secrets: |
            secret/ci ARM_SUBSCRIPTION_ID ;
            secret/ci AZURE_LOGIN ;
            secret/ci AZURE_SECRET ;
            secret/ci RESOURCE_GROUP ;
            secret/ci ACR ;
            secret/ci AKS ;
            secret/ci ACR_LINK ;

      - name: "Login to Azure CLI"
        run: |
          az login -u ${{ env.AZURE_LOGIN }} -p ${{ env.AZURE_SECRET }}

      - name: Login to ACR
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.ACR_LINK }}
          username: ${{ env.REGISTRY_USERNAME  }}
          password: ${{ env.REGISTRY_PASSWORD  }}

      - name: Delete image
        run: |
          az acr repository delete --name ${{ env.ACR }} --image adservice:v1 --yes
        continue-on-error: true

      - name: Building Ad Service 
        run: |
          cd src/adservice/
          docker build -t ${{ env.ACR_LINK }}/adservice:v1 .
          docker push ${{ env.ACR_LINK }}/adservice:v1