name: Building Ad Service

# Only trigger, when the build workflow succeeded
on:
  workflow_run:
    workflows: ["Continuous Integration - Push"]
    branches: [master]
    types:
      - completed

jobs:
  build-ad-service:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to ACR
        uses: azure/docker-login@v1
        with:
          login-server: boutiqueaksacr.azurecr.io
          username: b13b7e1c-e6d3-451f-8a32-740a18f29899
          password: 4YATHKLU8O7MUjq_fQpLuaxPmci8l3q3qm

      - name: Building Ad Service 
        run: |
          cd src/adservice/
          docker build -t boutiqueaksacr.azurecr.io/adservice:v1 .
          docker push boutiqueaksacr.azurecr.io/adservice:v1