name: Building Ad Service

# Only trigger, when the build workflow succeeded
on:
  workflow_run:
    workflows: ["Continuous Integration - Push"]
    types:
      - completed

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Building Ad Service
        run: |
          cd src/adservice/
          docker build -t boutiqueaksacr.azurecr.io/adservice:v1 .
          docker push boutiqueaksacr.azurecr.io/adservice:v1