name: 'Building Catalog service image'

on:
  push:
    branches:
    - master
    paths:
      - "src/productcatalogservice/Dockerfile"

jobs:
  Integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: "Login to Azure CLI"
        uses: azure/login@v1  
        with:
          creds: ${{ secrets.AZ_CRED }}

      - name: Login to ACR
        uses: azure/docker-login@v1
        with:
          login-server: boutiqueaksacr.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Delete image 
        run: |
          az acr repository delete --name boutiqueaksacr --image productcatalogservice:v1

      - name: Building Product Catalog Service
        run: |
          cd src/productcatalogservice/
          docker build -t boutiqueaksacr.azurecr.io/productcatalogservice:v1 .
          docker push boutiqueaksacr.azurecr.io/productcatalogservice:v1
