name: Continuous Delivery - Pull Request
on:
  pull_request:
    branches:
      - master
jobs:
  aksHelm:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: Login to AKS
        uses: azure/aks-set-context@v1
        with:
          creds: '{
                    "clientId": "b13b7e1c-e6d3-451f-8a32-740a18f29899",
                    "clientSecret": "4YATHKLU8O7MUjq_fQpLuaxPmci8l3q3qm",
                    "subscriptionId": "c4774376-bc4c-48e6-93eb-c0ac26c6345d",
                    "tenantId": "c8cd0425-e7b7-4f3d-9215-7e5fa3f439e8"
                  }'
          cluster-name: boutiqueaks
          resource-group: mario-robles
      
      - name: Helm install
        run: helm install boutique ./gpi
        working-directory: chart/