name: Continuous Delivery - Pull Request
on:
  pull_request:
    branches:
      - master
    types: [closed]
jobs:
  Deployment:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: Login to AKS
        uses: azure/aks-set-context@v1
        env:
          CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
        with:
          creds: ${{ env.CREDENTIALS }}
          cluster-name: boutiqueaks
          resource-group: mario-robles
      
      - name: "Login to Azure CLI"
        run: |
          az login -u ${{ secrets.AZURE_LOGIN }} -p ${{ secrets.AZURE_SECRET }}

      - name: Attaching Cluster
        run: |
          az aks update -n boutiqueaks -g mario-robles --attach-acr boutiqueaksacr

      - name: Checking the ACR
        run: |
          az aks check-acr -g mario-robles -n boutiqueaks  --acr boutiqueaksacr.azurecr.io

      - name: Helm install
        run: helm install boutique ./gpi
        working-directory: chart/