name: Continuous Delivery - Pull Request
on:
  pull_request:
    branches:
      - master
jobs:
  aksHelm:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: Login to AKS
        uses: azure/aks-set-context@v1
        env:
          CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
        with:
          creds: ${{ env.CREDENTIALS }}
          cluster-name: boutiqueaks
          resource-group: mario-robles
      
      - name: Helm install
        run: helm install boutique ./gpi
        working-directory: chart/