name: 'Checkout service image'

on:
  pull_request:
    branches:
    - dev
    - master
    types: [closed]
    paths:
      - "src/checkoutservice/"

jobs:
  Integration:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: ACTIONS_ALLOW_UNSECURE_COMMANDS
        id: ACTIONS_ALLOW_UNSECURE_COMMANDS
        run: echo 'ACTIONS_ALLOW_UNSECURE_COMMANDS=true' >> $GITHUB_ENV

      - name: Import Secrets
        uses: hashicorp/vault-action@v2.0.1
        with:
          url: http://vault.centralus.cloudapp.azure.com:8200/
          token: ${{ secrets.VAULT_TOKEN }}
          tlsSkipVerify: true
          secrets: |
            secret/ci AZURE_LOGIN ;
            secret/ci AZURE_SECRET ;
            secret/ci ACR ;
            secret/ci REGISTRY_USERNAME ;
            secret/ci REGISTRY_PASSWORD  ;

      - name: "Login to Azure CLI"
        run: |
          az login -u ${{ env.AZURE_LOGIN }} -p ${{ env.AZURE_SECRET }}

      - name: Login to ACR
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.ACR_LINK }}
          username: ${{ env.REGISTRY_USERNAME  }}
          password: ${{ env.REGISTRY_PASSWORD  }}

      - name: Images test building
        run: |
          echo "Testing images building"

      - name: Delete image 
        run: |
          az acr repository delete --name ${{ env.ACR }} --image checkoutservice:v1
        continue-on-error: true

      - name: Building Ad Service 
        run: |
          cd src/adservice/
          docker build -t ${{ env.ACR_LINK }}/checkoutservice:v1 .