name: Continuous Integration - Push

on: [push]

jobs:
  Integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      #- name: "Login to Azure CLI"
      #  uses: azure/login@v1  
      #  with:
      #    creds: ${{ AzLogin.ARM_SUBSCRIPTION_ID }}

      - name: Login to ACR
        uses: azure/docker-login@v1
        with:
          login-server: boutiqueaksacr.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}