name: Continuos Integration

on: [push]

jobs:
  buildImages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      #- name: "Login to Azure CLI"
      #  uses: azure/login@v1  
      #  with:
      #    creds: ${{ AzLogin.ARM_SUBSCRIPTION_ID }}

      - name: Login to ACR
        uses: azure/docker-login@v1
        with:
          login-server: boutiqueaksacr.azurecr.io
          username: b13b7e1c-e6d3-451f-8a32-740a18f29899
          password: 4YATHKLU8O7MUjq_fQpLuaxPmci8l3q3qm

      - name: Building Ad Service
        run: |
          cd src/adservice/
          docker build -t boutiqueaksacr.azurecr.io/adservice:v1 .
  #        docker push boutiqueaksacr.azurecr.io/adservice:v1

      - name: Building Cart Service
        run: |
          cd src/cartservice/src/
          docker build -t boutiqueaksacr.azurecr.io/cartservice:v1 .
  #       docker push boutiqueaksacr.azurecr.io/cartservice:v1

      - name: Building Checkout Service
        run: |
          cd src/checkoutservice/
          docker build -t boutiqueaksacr.azurecr.io/checkoutservice:v1 .
  #        docker push boutiqueaksacr.azurecr.io/checkoutservice:v1

      - name: Building Currency Service
        run: |
          cd src/currencyservice/
          docker build -t boutiqueaksacr.azurecr.io/currencyservice:v1 .
  #        docker push boutiqueaksacr.azurecr.io/currencyservice:v1

      - name: Building Email Service
        run: |
          cd src/emailservice/
          docker build -t boutiqueaksacr.azurecr.io/emailservice:v1 .
  #        docker push boutiqueaksacr.azurecr.io/emailservice:v1

      - name: Building Front-End
        run: |
          cd src/frontend/
          docker build -t boutiqueaksacr.azurecr.io/frontend:v1 .
  #        docker push boutiqueaksacr.azurecr.io/frontend:v1

      - name: Building Load Generator
        run: |
          cd src/loadgenerator/
          docker build -t boutiqueaksacr.azurecr.io/loadgenerator:v1 .
  #        docker push boutiqueaksacr.azurecr.io/loadgenerator:v1

      - name: Building Payment Service
        run: |
          cd src/paymentservice/
          docker build -t boutiqueaksacr.azurecr.io/paymentservice:v1 .
  #        docker push boutiqueaksacr.azurecr.io/paymentservice:v1

      - name: Building Product Catalog Service
        run: |
          cd src/productcatalogservice/
          docker build -t boutiqueaksacr.azurecr.io/productcatalogservice:v1 .
  #        docker push boutiqueaksacr.azurecr.io/productcatalogservice:v1

      - name: Building Recommendation service
        run: |
          cd src/recommendationservice/
          docker build -t boutiqueaksacr.azurecr.io/recommendationservice:v1 .
  #        docker push boutiqueaksacr.azurecr.io/recommendationservice:v1

      - name: Building Shipping Service
        run: |
          cd src/shippingservice/
          docker build -t boutiqueaksacr.azurecr.io/shippingservice:v1 .
  #        docker push boutiqueaksacr.azurecr.io/shippingservice:v1