name: Building Currency Service

# Only trigger, when the build workflow succeeded
on:
  workflow_run:
    workflows: ["Building Checkout Service"]
    branches: [master]
    types:
      - completed

jobs:
  build-currency-service:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to ACR
        uses: azure/docker-login@v1
        with:
          login-server: boutiqueaksacr.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Building Currency Service
        run: |
          cd src/currencyservice/
          docker build -t boutiqueaksacr.azurecr.io/currencyservice:v1 .
          docker push boutiqueaksacr.azurecr.io/currencyservice:v1