name: 'Building Payment service image'

on:
  push:
    branches:
    - master
    paths:
      - "src/paymentservice/"

jobs:
  Integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: "Login to Azure CLI"
        uses: azure/login@v1  
        with:
          creds: ${{ secrets.AZ_CRED }}

      - name: Login to ACR
        uses: azure/docker-login@v1
        with:
          login-server: boutiqueaksacr.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Delete image 
        run: |
          az acr repository delete --name boutiqueaksacr --image paymentservice:v1
        continue-on-error: true

      - name: Building Payment Service
        run: |
          cd src/paymentservice/
          docker build -t boutiqueaksacr.azurecr.io/paymentservice:v1 .
          docker push boutiqueaksacr.azurecr.io/paymentservice:v1
