name: Building Payment Service

# Only trigger, when the build workflow succeeded
on:
  workflow_run:
    workflows: ["Building Load Generator Service"]
    branches: [master]
    types:
      - completed

jobs:
  build-payment-service:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to ACR
        uses: azure/docker-login@v1
        with:
          login-server: boutiqueaksacr.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Building Payment Service
        run: |
          cd src/paymentservice/
          docker build -t boutiqueaksacr.azurecr.io/paymentservice:v1 .
          docker push boutiqueaksacr.azurecr.io/paymentservice:v1